# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Model_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Главное окно
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 743)

        # Основной виджет
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")

        MainWindow.setCentralWidget(self.mainWidget)

        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.menuWidget = QtWidgets.QTabWidget(self.mainWidget)
        self.menuWidget.setObjectName("menuWidget")
        self.verticalLayout.addWidget(self.menuWidget)

        # Разделы основного виджета (меню)
        self.menuTab = QtWidgets.QWidget()
        self.menuTab.setLayout(QtWidgets.QVBoxLayout())
        self.menuWidget.addTab(self.menuTab, "Main")

        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setLayout(QtWidgets.QVBoxLayout())
        self.menuWidget.addTab(self.settingsTab, "Settings")

        self.eventsTab = QtWidgets.QWidget()
        self.menuWidget.addTab(self.eventsTab, "Events")

        # Верхняя часть окна
        self.header = QtWidgets.QWidget()
        self.header.setLayout(QtWidgets.QHBoxLayout())

        # Верхняя часть окна - блок контроля портов
        self.portControls = QtWidgets.QGroupBox("Port controls")
        self.portControls.setObjectName("groupBox")
        self.portControls.setLayout(QtWidgets.QHBoxLayout())

        self.portSelect = QtWidgets.QComboBox()
        self.portSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.portSelect.addItem('Port 1')
        self.portSelect.addItem('Port 2')
        self.portSelect.addItem('Port 3')

        self.openPortBtn = QtWidgets.QPushButton('Open')
        self.openPortBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closePortBtn = QtWidgets.QPushButton('Close')
        self.closePortBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.portControls.layout().addWidget(self.portSelect)
        self.portControls.layout().addWidget(self.openPortBtn)
        self.portControls.layout().addWidget(self.closePortBtn)

        # Верхняя часть окна - блок MDI settings
        self.MdiSettings = QtWidgets.QGroupBox("MDI setting")
        self.MdiSettings.setObjectName("groupBox")
        self.MdiSettings.setLayout(QtWidgets.QHBoxLayout())

        self.tileWindows = QtWidgets.QPushButton('Tile windows')
        self.tileWindows.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.MdiSettings.layout().addWidget(self.tileWindows)

        self.header.layout().addWidget(self.portControls)
        self.header.layout().addWidget(self.MdiSettings)
        self.menuTab.layout().addWidget(self.header)

        #основная часть окна
        self.meas = QtWidgets.QWidget()
        self.meas.setLayout(QtWidgets.QHBoxLayout())

        self.signalOptions = QtWidgets.QGroupBox('Show signal')
        self.signalOptions.setLayout(QtWidgets.QVBoxLayout())
        self.signalOptions.setMinimumWidth(int(0.3 * MainWindow.width()))

        self.signalTable = QtWidgets.QTableWidget()
        self.timeMeas= QtWidgets.QGroupBox('Time Meas')
        self.timeMeas.setLayout(QtWidgets.QVBoxLayout())

        self.timeMeasRadio1 = QtWidgets.QRadioButton('Continuously')
        self.timeMeasRadio1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.timeMeasRadio2 = QtWidgets.QRadioButton('Fixed time')
        self.timeMeasRadio2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.timeMeasSelect = QtWidgets.QComboBox()
        self.timeMeasSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.timeMeasSelect.addItem('Time 1')
        self.timeMeasSelect.addItem('Time 2')
        self.timeMeasSelect.addItem('Time 3')

        self.timeMeasInput = QtWidgets.QLineEdit()
        self.timeMeasInput.setPlaceholderText('Put some text here')

        self.timeMeasProgress = QtWidgets.QProgressBar()

        self.timeMeasControlBtn = QtWidgets.QWidget()
        self.timeMeasControlBtn.setLayout(QtWidgets.QHBoxLayout())

        self.experimentDescrBox = QtWidgets.QGroupBox("Experiment description")
        self.experimentDescrBox.setLayout(QtWidgets.QVBoxLayout())
        self.experimentDescr = QtWidgets.QTextEdit()
        self.experimentDescrBox.layout().addWidget(self.experimentDescr)

        self.startMeasTime = QtWidgets.QPushButton('Start')
        self.startMeasTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopMeasTime = QtWidgets.QPushButton('Stop')
        self.stopMeasTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.timeMeasControlBtn.layout().addWidget(self.startMeasTime)
        self.timeMeasControlBtn.layout().addWidget(self.stopMeasTime)

        self.timeMeas.layout().addWidget(self.timeMeasRadio1)
        self.timeMeas.layout().addWidget(self.timeMeasRadio2)
        self.timeMeas.layout().addWidget(self.timeMeasSelect)
        self.timeMeas.layout().addWidget(self.timeMeasInput)
        self.timeMeas.layout().addWidget(self.timeMeasProgress)
        self.timeMeas.layout().addWidget(self.experimentDescrBox)
        self.timeMeas.layout().addWidget(self.timeMeasControlBtn)

        self.signalOptions.layout().addWidget(self.signalTable)
        self.signalOptions.layout().addWidget(self.timeMeas)

        self.signalCharts = QtWidgets.QMdiArea()

        self.meas.layout().addWidget(self.signalOptions)
        self.meas.layout().addWidget(self.signalCharts)
        self.menuTab.layout().addWidget(self.meas)

        # нижняя часть окна
        self.saveFile = QtWidgets.QGroupBox("Save file")
        self.saveFile.setLayout(QtWidgets.QVBoxLayout())

        self.saveFileSelectDir = QtWidgets.QWidget()
        self.saveFileSelectDir.setLayout(QtWidgets.QHBoxLayout())

        self.saveFileSelectDirBtn = QtWidgets.QPushButton('Select dir')
        self.saveFileSelectDirBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    
        self.saveFileSelectDirInput = QtWidgets.QLineEdit()
        self.saveFileSelectDirInput.setPlaceholderText('Write the path to the folder here')

        self.saveFileSelectDir.layout().addWidget(self.saveFileSelectDirBtn)
        self.saveFileSelectDir.layout().addWidget(self.saveFileSelectDirInput)

        self.saveFile.layout().addWidget(self.saveFileSelectDir)
        self.menuTab.layout().addWidget(self.saveFile)

        # окно настроек
        #controller
        self.controllerBox = QtWidgets.QGroupBox("Controller")
        self.controllerBox.setLayout(QtWidgets.QVBoxLayout())
        self.controllerBox.setMaximumHeight(100)
        self.controller = QtWidgets.QComboBox()
        self.controller.setMaximumHeight(50)
        self.controller.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.controller.addItem('Time 1')
        self.controller.addItem('Time 2')
        self.controller.addItem('Time 3')
        self.controllerBox.layout().addWidget(self.controller)

        # settigs ADC
        self.settigsAdcBox = QtWidgets.QGroupBox("Settings ADC")
        self.settigsAdcBox.setLayout(QtWidgets.QVBoxLayout())
        self.settigsAdcBoxself = QtWidgets.QWidget()
        self.A0Checkbox = QtWidgets.QCheckBox('A0')
        self.A1Checkbox = QtWidgets.QCheckBox('A1')
        self.A2Checkbox = QtWidgets.QCheckBox('A2')
        self.A3Checkbox = QtWidgets.QCheckBox('A3')
        self.A4Checkbox = QtWidgets.QCheckBox('A4')
        self.A5Checkbox = QtWidgets.QCheckBox('A5')
        self.ADS1015Checkbox = QtWidgets.QCheckBox('ADS1015')
        self.AHT25_x38Checkbox = QtWidgets.QCheckBox('AHT25_x38')
        self.settigsAdcBoxBtn = QtWidgets.QPushButton('Send')

        self.settigsAdcBox.layout().addWidget(self.A0Checkbox)
        self.settigsAdcBox.layout().addWidget(self.A1Checkbox)
        self.settigsAdcBox.layout().addWidget(self.A2Checkbox)
        self.settigsAdcBox.layout().addWidget(self.A3Checkbox)
        self.settigsAdcBox.layout().addWidget(self.A4Checkbox)
        self.settigsAdcBox.layout().addWidget(self.A5Checkbox)
        self.settigsAdcBox.layout().addWidget(self.ADS1015Checkbox)
        self.settigsAdcBox.layout().addWidget(self.AHT25_x38Checkbox)
        self.settigsAdcBox.layout().addWidget(self.settigsAdcBoxBtn)

        self.settingsTabMidleSection = QtWidgets.QWidget()
        self.settingsTabMidleSection.setLayout(QtWidgets.QHBoxLayout())

        self.settigsLinking = QtWidgets.QGroupBox("Linking with an external device")
        self.settigsLinking.setLayout(QtWidgets.QVBoxLayout())

        self.usb2 = QtWidgets.QRadioButton('USB 2')
        self.bluetooth = QtWidgets.QRadioButton('Bluetooth')
        self.wifi = QtWidgets.QRadioButton('WiFi')
        self.speed = QtWidgets.QLineEdit()
        self.speed.setPlaceholderText('Write speed value here')
        self.speedBlock = QtWidgets.QGroupBox("Speed")
        self.speedBlock.setMaximumHeight(50)
        self.speedBlock.setLayout(QtWidgets.QVBoxLayout())

        self.settigsLinking.layout().addWidget(self.usb2)
        self.settigsLinking.layout().addWidget(self.bluetooth)
        self.settigsLinking.layout().addWidget(self.wifi)
        self.speedBlock.layout().addWidget(self.speed)
        self.settigsLinking.layout().addWidget(self.speedBlock)

        self.settingsTabMidleSectionBlock = QtWidgets.QWidget()
        self.settingsTabMidleSectionBlock.setLayout(QtWidgets.QVBoxLayout())

        self.safeMode = QtWidgets.QGroupBox("Safe Mode")
        self.safeMode.setLayout(QtWidgets.QVBoxLayout())

        self.safeRadio1 = QtWidgets.QRadioButton('Radio1')
        self.safeRadio2 = QtWidgets.QRadioButton('Radio2')
        self.safeRadio3 = QtWidgets.QRadioButton('Radio3')
        self.safeRadio4 = QtWidgets.QRadioButton('Radio4')
        self.safeRadioBtn = QtWidgets.QPushButton('Send')

        self.safeMode.layout().addWidget(self.safeRadio1)
        self.safeMode.layout().addWidget(self.safeRadio2)
        self.safeMode.layout().addWidget(self.safeRadio3)
        self.safeMode.layout().addWidget(self.safeRadio4)
        self.safeMode.layout().addWidget(self.safeRadioBtn)

        self.settingsTabMidleSectionBlock.layout().addWidget(self.settigsLinking)
        self.settingsTabMidleSectionBlock.layout().addWidget(self.safeMode)

        self.settingsTabMidleSectionBlock2 = QtWidgets.QWidget()
        self.settingsTabMidleSectionBlock2.setLayout(QtWidgets.QVBoxLayout())

        self.dataSettingBox = QtWidgets.QGroupBox("Data Setting Meas")
        self.dataSettingBox.setLayout(QtWidgets.QVBoxLayout())
        self.dataSettingBox.setMaximumHeight(150)
        self.discrFreq = QtWidgets.QGroupBox("Sampling frequency, Hz")
        self.discrFreq.setLayout(QtWidgets.QVBoxLayout())
        self.discrFreqInput = QtWidgets.QLineEdit()
        self.discrFreqInput.setPlaceholderText("Write sampling frequency here")
        self.discrFreq.layout().addWidget(self.discrFreqInput)
        self.dataSettingBox.layout().addWidget(self.discrFreq)
        self.smoothing = QtWidgets.QCheckBox("smoothing")
        self.dataSettingBox.layout().addWidget(self.smoothing)

        self.visualEffectsBox = QtWidgets.QGroupBox("Visual Effects")
        self.visualEffectsBox.setLayout(QtWidgets.QVBoxLayout())

        self.chartPoints = QtWidgets.QGroupBox("Quantity points on the graph")
        self.chartPoints.setLayout(QtWidgets.QVBoxLayout())
        self.chartPointsInput = QtWidgets.QLineEdit()
        self.chartPointsInput.setPlaceholderText('Write quantity points here')
        self.chartPoints.layout().addWidget(self.chartPointsInput)

        self.thinning = QtWidgets.QGroupBox("Thinning")
        self.thinning.setLayout(QtWidgets.QVBoxLayout())
        self.thinningInput = QtWidgets.QLineEdit()
        self.thinningInput.setPlaceholderText('Write thinning here')
        self.thinning.layout().addWidget(self.thinningInput)

        self.drawDelay = QtWidgets.QGroupBox("Draw delay, s")
        self.drawDelay.setLayout(QtWidgets.QVBoxLayout())
        self.drawDelayInput = QtWidgets.QLineEdit()
        self.drawDelayInput.setPlaceholderText('Write draw delay here')
        self.drawDelay.layout().addWidget(self.drawDelayInput)

        self.visualEffectsBox.layout().addWidget(self.chartPoints)
        self.visualEffectsBox.layout().addWidget(self.thinning)
        self.visualEffectsBox.layout().addWidget(self.drawDelay)

        self.settingsTabMidleSectionBlock2.layout().addWidget(self.dataSettingBox)
        self.settingsTabMidleSectionBlock2.layout().addWidget(self.visualEffectsBox)

        self.settingsTabMidleSection.layout().addWidget(self.settigsAdcBox)
        self.settingsTabMidleSection.layout().addWidget(self.settingsTabMidleSectionBlock)
        self.settingsTabMidleSection.layout().addWidget(self.settingsTabMidleSectionBlock2)

        self.settingsTab.layout().addWidget(self.controllerBox)
        self.settingsTab.layout().addWidget(self.settingsTabMidleSection)
        # self.retranslateUi(MainWindow)
        # self.tabWidget.setCurrentIndex(0)
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Port.setText(_translate("MainWindow", "Порт"))
        self.pushButton_Open_Port.setText(_translate("MainWindow", "Open"))
        self.pushButton_4.setText(_translate("MainWindow", "Close"))
        self.label_Show_Signals.setText(_translate("MainWindow", "Отобразить сигнал"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_11.setText(_translate("MainWindow", "Время измерения"))
        self.radioButton_8.setText(_translate("MainWindow", "Непрерывно"))
        self.radioButton_9.setText(_translate("MainWindow", "Фикс. врем."))
        self.pushButton_5.setText(_translate("MainWindow", "Start"))
        self.pushButton_6.setText(_translate("MainWindow", "Stop"))
        self.label_12.setText(_translate("MainWindow", "Запись в файл"))
        self.pushButton_7.setText(_translate("MainWindow", "Select dir"))
        self.label_13.setText(_translate("MainWindow", "File"))
        self.checkBox_9.setText(_translate("MainWindow", "Запись"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.label_2.setText(_translate("MainWindow", "Настройка АЦП"))
        self.checkBox.setText(_translate("MainWindow", "A0"))
        self.checkBox_2.setText(_translate("MainWindow", "A1"))
        self.checkBox_3.setText(_translate("MainWindow", "A2"))
        self.checkBox_4.setText(_translate("MainWindow", "A3"))
        self.checkBox_5.setText(_translate("MainWindow", "A4"))
        self.checkBox_6.setText(_translate("MainWindow", "A5"))
        self.checkBox_7.setText(_translate("MainWindow", "ADS1015"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.label_3.setText(_translate("MainWindow", "Контроллер"))
        self.label_4.setText(_translate("MainWindow", "SafeMode"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_4.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton_2.setText(_translate("MainWindow", "Send"))
        self.label_5.setText(_translate("MainWindow", "Связь с внешним устройством"))
        self.radioButton_5.setText(_translate("MainWindow", "USB 2"))
        self.radioButton_6.setText(_translate("MainWindow", "Bluetooth"))
        self.radioButton_7.setText(_translate("MainWindow", "RadioButton"))
        self.label_6.setText(_translate("MainWindow", "Скорость"))
        self.label.setText(_translate("MainWindow", "Данные"))
        self.label_7.setText(_translate("MainWindow", "Частота дискретизации, Гц"))
        self.checkBox_8.setText(_translate("MainWindow", " Сглаживать CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Events"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setWindowTitle('Sensor Monitor')
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())
